apiVersion: v1
data:
  application.properties: |
    FOO=bar
kind: ConfigMap
metadata:
  labels:
    app: nong-kai
    env: prod
  name: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nong-kai
    env: prod
  name: my-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nong-kai
      env: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nong-kai
        env: prod
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
