apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eureka
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka
    spec:
      containers:
      - image: netflixoss/eureka:1.3.1
        name: eureka
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "150m"
status: {}
